name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install lilypond
      run: |
        apt-get update && apt-get install lilypond
    - name: Compile score
      run: |
        lilypond jinglebells.ly
    - name: Upload PDF score
        uses: actions/upload-artifact@v1
        with:
          name: jinglebells
          path: jinglebells.pdf


