name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update base images
      run: |
        sudo apt-get --yes update
        sudo apt-get --yes upgrade
        sudo apt-get --yes autoremove
    - name: Install lilypond
      run: |
        sudo apt-get install lilypond
    - name: Set embedding Japanese font inside PDFs
      run: |
        sudo apt-get --yes --no-install-recommends install texlive-lang-japanese
        sudo cjk-gs-integrate
        sudo kanji-config-updmap-sys ipa
    - name: Compile score
      run: |
        lilypond jinglebells.ly
    - name: Upload PDF score
      uses: actions/upload-artifact@v1
      with:
        name: jinglebells
        path: jinglebells.pdf


